version: 2

sources:
  - name: adventureworks-378020 
    description: Banco réplica do erp da adventureworks
    schema: sap_adw
    tables:
      - name: creditcard 
        columns:
          - name: creditcardid
            tests:
            - unique
            - not_null 
             					
          - name: cardtype

          - name: cardnumber

          - name: expmonth

          - name: expyear

          - name: modifieddate

      - name: customer
        columns:
          - name: customerid
            tests:
            - unique
            - not_null

      - name: address 
        columns:
          - name: creditcardid
            tests:
            - unique
            - not_null

      - name: stateprovince
        columns:
          - name: creditcardid
            tests:
            - unique
            - not_null

      - name: currency
        columns:
          - name: creditcardid
            tests:
            - unique
            - not_null

      - name: salesorderdetail
        columns:
          - name: creditcardid
            tests:
            - unique
            - not_null

      - name: salesorderheader
        columns:
          - name: creditcardid
            tests:
            - unique
            - not_null

      - name: salesorderheadersalesreason
        columns:
          - name: creditcardid
            tests:
            - unique
            - not_null

      - name: countryregion
        columns:
          - name: creditcardid
            tests:
            - unique
            - not_null

      - name: person
        columns:
          - name: creditcardid
            tests:
            - unique
            - not_null

      - name: product
        columns:
          - name: creditcardid
            tests:
            - unique
            - not_null

      - name: productcategory
        columns:
          - name: creditcardid
            tests:
            - unique
            - not_null

      - name: productsubcategory
        columns:
          - name: creditcardid
            tests:
            - unique
            - not_null

      - name: currencyrate 
        columns:
          - name: creditcardid
            tests:
            - unique
            - not_null
            
      - name: salesreason 
        columns:
          - name: creditcardid
            tests:
            - unique
            - not_null